version: '3.8' 
services:
	build: 
		context: .
		dockerfile: backend/apollo-server-graphql-prisma/Dockerfile
	volumes: 
		- '.:/app'
		- '/app/node_modules'
	ports: 
		-3001:3000
	environment: 
		- CHOKIDAR_USEPOLLING=true
	