version: "3.1"
services:
  # testDb:
  #   image: postgres
  #   restart: always
  #   volumes:
  #     - ./docker_data/db_data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: admin
  #     POSTGRES_USER: admin
  #     POSTGRES_DB: pos_test
  #   ports:
  #     - 5431:5432
  db:
    image: postgres
    restart: always
    volumes:
      - ./docker_data/db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8090:8080
  express:
    build: .
    command: npm run start
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
